  const routes = ["dashboard", "providers/add", "providers", "desktop", "proxy", "settings", "guide"];
  const restartReminderStorageKey = "ccds.restartReminder.dismissed";
  const contractData = window.CCDS_CONTRACTS;
  if (!contractData) {
    throw new Error("Generated frontend contracts are missing");
  }
  const modelMeta = contractData.modelMeta;
  const providerFormModelSlots = contractData.providerFormModelSlots;
  const availableThemes = ["default", "green", "orange", "gray", "dark", "white"];
  const providerAuthSchemes = ["bearer", "x-api-key", "none"];
  const providerFormDefaultRows = contractData.providerFormDefaultRows;
  let pendingDeleteId = null;
  let selectedPreset = null;
  let presetCache = [];
  let formApiFormat = "Anthropic";
  let formModelCapabilities = {};
  let formRequestOptions = {};
  let providerFormMappings = {};
  let providerFormRows = [...providerFormDefaultRows];
  let providerAvailableModels = [];
  let openProviderSlotMenuIndex = null;
  let openProviderModelMenuKey = null;
  let protocolDetected = false;
  let baseUrlMenuOpen = false;
  let authSchemeMenuOpen = false;
  let editingProviderId = null;
  let deleteModal = null;
  let confirmModal = null;
  let restartReminderModal = null;
  let feedbackBsModal = null;
  let feedbackAttachments = [];
  let toast = null;
  let updateCheckCache = null;
  let updateInstallPhase = "idle";
  let ccSwitchCandidates = [];
  let proxyLogTimer = null;
  let proxyLogInflight = false;
