use std::{
    collections::BTreeSet,
    env,
    error::Error,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
};

mod contracts;
mod release;

const APP_FRAGMENTS: &[&str] = &[
    "frontend/js/app/00-state.js",
    "frontend/js/app/10-ui-core.js",
    "frontend/js/app/20-routes.js",
    "frontend/js/app/30-settings-import.js",
    "frontend/js/app/40-actions.js",
    "frontend/js/app/50-feedback-bootstrap.js",
];

const STYLE_FRAGMENTS: &[&str] = &[
    "frontend/css/style/00-foundation.css",
    "frontend/css/style/10-components.css",
    "frontend/css/style/20-responsive.css",
    "frontend/css/style/30-palette-layout-refinement.css",
    "frontend/css/style/40-dashboard-provider-lists.css",
    "frontend/css/style/50-forms-and-utility-pages.css",
    "frontend/css/style/60-settings-guide-responsive.css",
];

const APP_BANNER: &str =
    "// Generated by xtask frontend bundle-app. Edit frontend/js/app/*.js instead.\n";
const STYLE_BANNER: &str =
    "/* Generated by xtask frontend bundle-style. Edit frontend/css/style/*.css instead. */\n";

type DynResult<T> = Result<T, Box<dyn Error>>;

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> DynResult<()> {
    let root = repo_root()?;
    let args = env::args().skip(1).collect::<Vec<_>>();

    match args.as_slice() {
        [command] if command == "build" => build_frontend(&root),
        [command] if command == "check-static" => check_static_contracts(&root),
        [area, command] if area == "frontend" && command == "build" => build_frontend(&root),
        [area, command] if area == "frontend" && command == "bundle-app" => {
            write_app_bundle(&root, false)
        }
        [area, command, flag]
            if area == "frontend" && command == "bundle-app" && flag == "--check" =>
        {
            write_app_bundle(&root, true)
        }
        [area, command] if area == "frontend" && command == "bundle-style" => {
            write_style_bundle(&root, false)
        }
        [area, command, flag]
            if area == "frontend" && command == "bundle-style" && flag == "--check" =>
        {
            write_style_bundle(&root, true)
        }
        [area, command] if area == "frontend" && command == "check-contracts" => {
            check_static_contracts(&root)
        }
        [area, rest @ ..] if area == "release" => release::run_release(&root, rest),
        [area, rest @ ..] if area == "package" => release::run_package(&root, rest),
        _ => {
            print_usage();
            Err("unknown xtask command".into())
        }
    }
}

fn repo_root() -> DynResult<PathBuf> {
    let mut current = env::current_dir()?;
    loop {
        if current.join("package.json").is_file() && current.join("frontend").is_dir() {
            return Ok(current);
        }
        if !current.pop() {
            return Err("could not find repository root from current directory".into());
        }
    }
}

fn print_usage() {
    eprintln!(
        "usage:
  cargo run -p xtask -- frontend build
  cargo run -p xtask -- frontend bundle-app [--check]
  cargo run -p xtask -- frontend bundle-style [--check]
  cargo run -p xtask -- frontend check-contracts
  cargo run -p xtask -- release windows [--version <version>] [--build] [--try-installer]
  cargo run -p xtask -- release verify --file <path>
  cargo run -p xtask -- package macos [--version <version>] [--app <path>]"
    );
}

fn build_frontend(root: &Path) -> DynResult<()> {
    contracts::generate_contract_files(root, false)?;
    write_app_bundle(root, false)?;
    write_style_bundle(root, false)?;

    let dist = root.join("dist");
    if dist.exists() {
        fs::remove_dir_all(&dist)?;
    }
    fs::create_dir_all(&dist)?;
    copy_dir(&root.join("frontend"), &dist)?;

    let bridge = dist.join("js/tauri-api.js");
    if !bridge.is_file() {
        return Err(format!("missing required frontend bridge: {}", bridge.display()).into());
    }

    Ok(())
}

fn write_app_bundle(root: &Path, check: bool) -> DynResult<()> {
    let generated = generate_from_fragments(root, APP_BANNER, APP_FRAGMENTS, true)?;
    let target = root.join("frontend/js/app.js");
    write_or_check(&target, &generated, check, "frontend/js/app.js")
}

fn write_style_bundle(root: &Path, check: bool) -> DynResult<()> {
    let generated = generate_from_fragments(root, STYLE_BANNER, STYLE_FRAGMENTS, false)?;
    let target = root.join("frontend/css/style.css");
    write_or_check(&target, &generated, check, "frontend/css/style.css")
}

fn generate_from_fragments(
    root: &Path,
    banner: &str,
    fragments: &[&str],
    wrap_in_closure: bool,
) -> DynResult<String> {
    let mut body = String::new();
    for (index, fragment) in fragments.iter().enumerate() {
        if index > 0 {
            body.push_str("\n\n");
        }
        body.push_str(read_trimmed_end(&root.join(fragment))?.as_str());
    }

    if wrap_in_closure {
        Ok(format!("{banner}(function () {{\n{body}\n}})();\n"))
    } else {
        Ok(format!("{banner}{body}\n"))
    }
}

fn read_trimmed_end(path: &Path) -> DynResult<String> {
    let source = fs::read_to_string(path)?;
    Ok(source.trim_end().to_string())
}

fn write_or_check(
    target: &Path,
    generated: &str,
    check: bool,
    display_name: &str,
) -> DynResult<()> {
    if check {
        let current = fs::read_to_string(target)?;
        if current != generated {
            return Err(format!(
                "{display_name} is out of date. Run pnpm build to regenerate it from source fragments."
            )
            .into());
        }
        return Ok(());
    }

    fs::write(target, generated)?;
    Ok(())
}

fn copy_dir(source: &Path, target: &Path) -> DynResult<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let path = entry.path();
        if path.file_name() == Some(OsStr::new(".DS_Store")) {
            continue;
        }

        let target_path = target.join(entry.file_name());
        if path.is_dir() {
            fs::create_dir_all(&target_path)?;
            copy_dir(&path, &target_path)?;
        } else {
            fs::copy(&path, &target_path)?;
        }
    }

    Ok(())
}

fn check_static_contracts(root: &Path) -> DynResult<()> {
    contracts::generate_contract_files(root, true)?;
    write_app_bundle(root, true)?;
    write_style_bundle(root, true)?;

    let index_html = text(root, "frontend/index.html")?;
    let app_js = text(root, "frontend/js/app.js")?;
    let bridge_js = text(root, "frontend/js/tauri-api.js")?;
    let package_json = text(root, "package.json")?;
    let release_workflow = text(root, ".github/workflows/release.yml")?;
    let windows_build = text(root, "windows/build.bat")?;
    let tauri_config = text(root, "src-tauri/tauri.conf.json")?;
    let rust_lib = text(root, "src-tauri/src/lib.rs")?;

    ensure(
        index_html.contains(r#"<script src="js/tauri-api.js"></script>"#),
        "frontend/index.html must load the Tauri API bridge directly",
    )?;
    ensure(
        index_html.contains(r#"<script src="js/generated/contracts.js"></script>"#),
        "frontend/index.html must load the generated contract constants before app.js",
    )?;
    ensure(
        !index_html.contains("js/api.js"),
        "frontend/index.html must not load the retired Python API wrapper",
    )?;
    ensure(
        !package_json.contains("src/originalApiBridge.js") && !package_json.contains("js/api.js"),
        "Tauri frontend build must not depend on the retired bridge replacement path",
    )?;

    let called_methods = called_ccapi_methods(&app_js);
    let missing_methods = called_methods
        .iter()
        .filter(|method| !has_bridge_method(&bridge_js, method))
        .cloned()
        .collect::<Vec<_>>();
    ensure(
        missing_methods.is_empty(),
        &format!(
            "frontend/js/tauri-api.js is missing CCApi methods used by app.js: {}",
            missing_methods.join(", ")
        ),
    )?;
    let missing_contract_methods = contracts::ccapi_methods()
        .iter()
        .filter(|method| !has_bridge_method(&bridge_js, method))
        .copied()
        .collect::<Vec<_>>();
    ensure(
        missing_contract_methods.is_empty(),
        &format!(
            "frontend/js/tauri-api.js is missing CCApi methods from the Rust-maintained bridge contract: {}",
            missing_contract_methods.join(", ")
        ),
    )?;
    let rust_commands = tauri_generate_handler_commands(&rust_lib);
    let bridge_commands = called_tauri_commands(&bridge_js);
    let missing_commands = bridge_commands
        .iter()
        .filter(|command| !rust_commands.contains(*command))
        .cloned()
        .collect::<Vec<_>>();
    ensure(
        missing_commands.is_empty(),
        &format!(
            "frontend/js/tauri-api.js calls Tauri commands not registered in Rust generate_handler: {}",
            missing_commands.join(", ")
        ),
    )?;

    ensure(
        bridge_js.contains("window.CCApi = {"),
        "Tauri bridge must expose window.CCApi",
    )?;
    ensure(
        !bridge_js.contains("127.0.0.1:18081"),
        "Tauri bridge must not call the retired Python admin server",
    )?;
    ensure(
        app_js.contains("CCApi.submitFeedback"),
        "Feedback UI must remain wired to the API bridge",
    )?;
    ensure(
        app_js.contains("applyProviderToDesktop"),
        "One-click provider apply flow must remain wired",
    )?;
    ensure(
        !release_workflow.contains("actions/setup-python"),
        "Release workflow must not install Python",
    )?;
    ensure(
        !release_workflow.contains("requirements.txt"),
        "Release workflow must not install Python requirements",
    )?;
    ensure(
        windows_build.contains("pnpm tauri build"),
        "Windows helper must build Tauri artifacts",
    )?;
    ensure(
        !windows_build.to_lowercase().contains("pyinstaller"),
        "Windows helper must not call PyInstaller",
    )?;
    ensure(
        tauri_config.contains(r#""installMode": "currentUser""#),
        "Windows Tauri installer must stay per-user",
    )?;

    println!(
        "Static contracts passed for {} CCApi methods.",
        called_methods.len()
    );
    Ok(())
}

fn text(root: &Path, path: &str) -> DynResult<String> {
    Ok(fs::read_to_string(root.join(path))?)
}

fn ensure(condition: bool, message: &str) -> DynResult<()> {
    if condition {
        Ok(())
    } else {
        Err(message.to_string().into())
    }
}

fn called_ccapi_methods(source: &str) -> BTreeSet<String> {
    let mut methods = BTreeSet::new();
    let mut rest = source;

    while let Some(index) = rest.find("CCApi.") {
        let after_prefix = &rest[index + "CCApi.".len()..];
        let method_len = after_prefix
            .chars()
            .take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '_' || *ch == '$')
            .map(char::len_utf8)
            .sum::<usize>();

        if method_len > 0 {
            let method = &after_prefix[..method_len];
            let after_method = after_prefix[method_len..].trim_start();
            if after_method.starts_with('(') {
                methods.insert(method.to_string());
            }
        }

        rest = &after_prefix[method_len..];
    }

    methods
}

fn has_bridge_method(source: &str, method: &str) -> bool {
    let method_len = method.len();
    let mut rest = source;

    while let Some(index) = rest.find(method) {
        let before = rest[..index].chars().next_back();
        let after = rest[index + method_len..].chars().next();
        let starts_at_boundary = before.is_none_or(|ch| !is_js_ident(ch));
        let ends_at_boundary = after.is_none_or(|ch| !is_js_ident(ch));

        if starts_at_boundary && ends_at_boundary {
            let before_window = &rest[..index];
            let before_trimmed = before_window.trim_end();
            let before_is_async_method = before_trimmed.ends_with("async");
            let after_method = rest[index + method_len..].trim_start();
            let method_definition = before_is_async_method && after_method.starts_with('(')
                || after_method.starts_with(':')
                || after_method.starts_with(',');
            if method_definition {
                return true;
            }
        }

        rest = &rest[index + method_len..];
    }

    false
}

fn is_js_ident(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_' || ch == '$'
}

fn called_tauri_commands(source: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    for marker in ["call('", "call(\""] {
        let quote = marker.chars().last().expect("marker quote");
        let mut rest = source;
        while let Some(index) = rest.find(marker) {
            let after_marker = &rest[index + marker.len()..];
            if let Some(end) = after_marker.find(quote) {
                commands.insert(after_marker[..end].to_string());
                rest = &after_marker[end + quote.len_utf8()..];
            } else {
                break;
            }
        }
    }
    commands
}

fn tauri_generate_handler_commands(source: &str) -> BTreeSet<String> {
    let Some(start) = source.find("tauri::generate_handler![") else {
        return BTreeSet::new();
    };
    let after_start = &source[start + "tauri::generate_handler![".len()..];
    let Some(end) = after_start.find("]") else {
        return BTreeSet::new();
    };
    after_start[..end]
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}
